### ISSUE TITLE
Insert newlines in Hex representation

### ISSUE THREAD

**Issue by hajdbo** [EUA/wxHexEditor#1]
What do you think about letting the user insert newlines in the Hex/Ascii display ?
It would allow "logical" separation between binary headers, binary data and CRC for example.

It would have been super useful in a recent reverse-engineering of a binary thrift message. If I could have aligned my data visually, it would have been easier to understand.

**Comment by EUA** [comment]
What Tags used for? You can mark any portion with colors and it's done.

Inserting new lines means inserting bytes to actual file and wxHexEditor already support it.

But I think you are talking about something different, but I don't think If I am understand you fully.

You are better to "make it" via photoshop like illustration tool and explain on a picture.
If I can get the idea, might i can code it later.

**Comment by hajdbo** [comment]
Here is a concept representation
![image](https://cloud.githubusercontent.com/assets/1834306/6896904/19fca244-d6f0-11e4-9693-05894facf3aa.png)

The idea is to introduce "virtual end-of-line" in the display (not in the file).

**Comment by EUA** [comment]
Thank you for illustration.

I want to ask some questions at my mind:
1. What happen if virtual end of line offset became real end of line? Do we need add an extra line or not?
2. What if we keep scrolling down to offset ~500 in this example. Does it need to be shown as 0x500 or 0x50C?
 * If it became 0x50C than we need to handle goto() function to compensate that error. Because it might be 50x Virtual EOL req. at top. 

Such a functionality requires re-design on this functions, I believe it is the biggest problem.:
* Mouse click location functions at wxHexCtrl class
 * wxHexCtrl::InternalPositionToVisibleCoord()
 * wxHexCtrl::PixelCoordToInternalPosition()
 * wxHexCtrl::PixelCoordToInternalCoord()

* wxHexCtrl clas painting functions
 * wxHexCtrl::UpdateDC()
 * wxHexCtrl::TagPainter()
are need to add break line processing code.

* Other necessities are
 * Adding a VirtualEndOfLine int64_t vector need to be defined at HexEditorCtrl & wxHexCtrl classes and addition that vector into TAGS file.
 * Add special function to HexEditorCtrl to handle wxHexCtrl class about if any VirtualEndOfLine in sight.
 * Add VirtualEndOfLine Panel for traction VEoL points.

I believe those are only visible part of the Iceberg. But end of the day, it's possible to do it and this is how to do, with wxHexEditor source.

I can say that it's possible to do show hex like that but indeed it popups more issues than it solves.
Unfortunately, I think that I am not gonna implement this, at least right now. If it became main requested feature that every one want to have it or I get bored and find nothing to do, l will look what I can :)

**Comment by prusswan** [comment]
I think the most important thing is to display the newline characters correctly (just like any other valid characters). Usually I do the text editing (including adding of newlines) via Sublime Text, so having a full ascii editing mode in the hex editor is not so important.

**Comment by EUA** [comment]
You are hundred percent correct for any text editor, but I have doubts if it's proper way to show newline character as you illustrated above.
Well this is might be a plus for wxHexEditor but in my decision it's overkill for an hex editor. :8ball:

**Comment by EUA** [comment]
Decided not to implement this.
