### ISSUE TITLE
"Find" button not working

### ISSUE THREAD

**Issue by jumpjack** [EUA/wxHexEditor#114]
FIND button in search dialog is not properly working: wrong characters are highlighted upon finding!
FIND ALL button is working fine instead.

Note: FIND NEXT is missing, both as a button, as a menu item and a shortcut (usually F3).

Version 0.24 on Windows 10.

**Comment by EUA** [comment]
I believe this fixed in 8046e8b013aa90b8c70700b4a98ee7c30e20e17f https://github.com/EUA/wxHexEditor/issues/100

**Comment by EUA** [comment]
Now checked and looks working...

Find NEXT? Nah not needed. You can just press the find button again. If cursor is already on the test that is searching for, program will search next (or previous one if you switched backward flag)

But replay last search without opening find dialog is meaningful. I might add F3 as find's shortcut without open search a dialog... Well, dialog need to be opened since search functions at there but I...
I might hide it. Can I?

Also a quick search dialog could be used with up and down buttons... Like gedit.
