### ISSUE TITLE
Change the format used for tags

### ISSUE THREAD

**Issue by KOLANICH** [EUA/wxHexEditor#125]
XML is too heavyweight. Maybe CBOR or MSGpack. Or SQLite. Or even better - a custom binary format. For parsing you can rely on Kaitai, for serializing you would have to code a serializer. Shouldn't be to hard though, the format gonna be damn simple.

**Comment by MarcinWieczorek** [comment]
I'd prefer something text-based in case someone wants to generate the tags based on their current understanding of the format and test their correctness by hand (or the eye).

**Comment by KOLANICH** [comment]
Then JSON or JSON5. Or there are some new-age formats, but JSON has the most impls over languages.

**Comment by MarcinWieczorek** [comment]
+1 for all three.

**Comment by EUA** [comment]
Binary format? No thanks!

I am not familiar with YAML or JSON(whats the 5 dude!) due not being a HTML/WebDev guy. :D
Yes we can change it but what if someone wants the XML back?

Now just make a quick research on those formats and found their brothers like TOML,CSON... also I feel that, If I ask "**which one is the best?**" than probably ignite another war on internet...
Here is a good comparison: https://gohugohq.com/howto/toml-json-yaml-comparison/

I choose XML due future-proofness and easy to work with other programs.
I also thought that, this format will support custom dynamic template files with it at future. Yes, I accept that other formats looks MUCH better to eye. But I don't intended to generate tags manually via text editor or examine them on notepad.

And the most important part is: wxWidgets has an internal toolkit to parse/generate XML (via wxXmlDocument class). I don't like the idea of using another library just for import/export tags. It looks like easy to program it but does it worth since we have a working mechanism?

Kaitai struct on my mind while it offered at Issue #20
When I start to work on dynamic templates for auto-generating tags, will make research on it.
