### ISSUE TITLE
CMake support, C++ version

### ISSUE THREAD

**Issue by tehKaiN** [EUA/wxHexEditor#156]
Hi there,

I've successfully added CMake build system to your project and built it by myself. Would you be interested in merging a pull request?

Also, since I'm interested in adding some features by myself, I see that you're using -std=c++0x which is kinda outdated. Is it a hard requirement (e.g. your compiler version supports only this one) or are you willing to increase std to something like c++17 (as supported by e.g. mingw-w64 gcc 7.1.0)?

Fun fact: CMake is crossplatform in a nice way, can generate makefiles, msbuild files and codeblocks project files. Perhaps it would be a nice base for having unified, universal build script?

**Comment by EUA** [comment]
Hi @tehKaiN ,
Thanks for interesting with wxHexEditor
-std=c++0x ?
I think it left at C::B config file.
I just use makefile to prepare binaries.

And for C::B config files, I could add anything even c++20, if exists.
I don't know if older compilers loves that.
At the end of the day, code need to be compiled with the current Makefile,
without adding -std=c++0x...

replacing all && with and, and all ! with not looks good to my eye but... I heard it make problems with Visual Studio. At least with older versions.

CMake... I don't not like add another dependency to build code indeed.Just look your fork and see nothing.  Yes might be superior build system to current one but what happen if there are problem arise later? I use CMake to compile some programs before but I prefer old make... I don't know how it works. Will I have passion to learn it? Nope. I think I start to became old and not like new things as it before... Depending on my current feeling, I want to add it only if it really necessary.

**Comment by tehKaiN** [comment]
Yeah, I've found the c++0x flag in c::b config. I rather specify the C++ standard in build configs in explicit way so that I get same experience across platforms. This also ensures that other contributors know exactly which language features to use or not.

I've updated my fork by pushing `cmake` branch right now. Feel free to look at it - I've also fixed some warnings which my compiler have yelled at me.

> replacing all && with and, and all ! with not looks good to my eye but... I heard it make problems with Visual Studio. At least with older versions.

huh? Where have I mentioned that? It's not even a C/C++ standard. ;)

If you don't plan to add CMake support it's okay with me, but it's only 3 short "CMakeLists.txt" file - nothing more added to the sources. I'll tell you some more stuff about why I use it. If you look at CMakeLists and then at your makefile - CMake doesn't use any `ls`  or other linuxey commands to do file manipulation and uses its own builtin tools across all platforms - this way I can compile this project without messing up my windows os with cygwin/msys/wsl or any other stuff which brings *nix commands. For me, that's the biggest feature of this build system. The second is the dependency included. I can import wxwidgets install and specify link libraries (wxaui etc.) using one line, provided I've compiled and installed wx libs using cmake first. And building wx using CMake was a very easy for me too. Thirdly, makefile syntax is too hellish for me. But that's just my personal experience. :)

Anyway, do anything you like about it, but expect some pull requests from me about more serious things. :)

**Comment by leroivi** [comment]
Hello,
I'm studying the project to see if I'm able to bring a contribution, I'm taking an overall look at it.
If I may put my two cents in this topic,
I think that make tool is a more restrictive build dependency than CMake since it's not meant to be cross-platform. Moreover CMake is such popular and well-integrated in major IDEs that makes it a _de-facto_ standard C++ build system, it's not an exotic one (even though I like meson, premake or Scons for using true scripting language instead of a custom config syntax).
I think it would be a great improvement that would permit developpers to use their favorite tools, especially on windows where the usage of *nix tools is a little complex, and that was also for that reason that the cross-build to windows is more convenient but with CMake it wouldn't be more difficult to make a native build. Also, once learnt, CMake is easier to maintain concerning the multi-platform support than makefile (that's its purpose).
Obviously, if the mains and regular contributors (aka you @EUA ^^) aren't familiar to this tool and don't want to be, this migration of build system would be couterproductive, but, yeah, you get my opinion, I think the effort would be very worth it, and considering that as a supplementary dependency should be compared with the dependancies that make implies.

About the CMake implementation that @tehKaiN ask for a pull request, I would like to put a warning that it didn't change only the build system of wxHexEditor but also the ones of mhash and udis86 which are other projects (that's why he made 3 differents CMakeLists), and I don't get the policy the project have about the inclusion of these libraries. Instead of being forked and maintained to keep them alive, and still managed as submodules, you decided to copy their base code in yours. What does that mean ? Do you allow them to be modified and improved or do you keep them here in the last state, waiting to be replaced by an active alternative ?

That being said, the CMakeLists.txt seems pretty lean and their simplicity is convincing in favor of CMake build system, good job ^^

> > replacing all && with and, and all ! with not looks good to my eye but... I heard it make problems with Visual Studio. At least with older versions.
> 
> huh? Where have I mentioned that? It's not even a C/C++ standard. ;)

Actually I think [it is](https://en.cppreference.com/w/cpp/language/operator_alternative), but neither do I see the link with the CMake topic ^^

**Comment by tehKaiN** [comment]
Oh yeah, I forgot about those alternative operators for platforms with limited speical char support. But I've never seen them used in nature? ;)

Regarding switching to cmake - I don't think it's necessary to do a switch - let it just be an alternative build system. If contributors will use them, it will be fine, otherwise it will stop working, decay and die of natural causes. Many projects use different build options which not always worked out of the box from version to version.

And regarding submodules - when I looked at them I haven't seen seen more recent version of mhash on github so I think it's safe to assume it's no longer developed and can be used as it is right now, but udis86 is maintained and having it as a submodule would be an improvement - we could integrate newer versions by bumping submodule reference to newer commit, perhaps even contributing something back from time to time.

**Comment by EUA** [comment]
Hi All.
I am not against CMake. But it's better to stick old good makefile for me.
CMake could be added as an alternative build mechanism, if it doesn't break anything or add any dependency. I am okay with it. My point is, since we have already working mechanisms, (C::B and makefile) why do we need another one... Now found your CMake files. Not looking too complex comparing to makefile.

About libraries @leroivi , mhash and udis86 both dead. And they are hard to build with original state. I needed to make some modifications on their make files to make it working. So I included them all to keep those changes. I also thought on dropping those directories and add again as git submodules(?  I think there are such mechanism on git, right?) Well, udis86 will be dropped very soon. Probably after release. I will switch to some other lib that supports other architectures other than x86 (capstone). Any of you willing to build CMake file for new library? Ah not needed. It has already.

**Comment by tehKaiN** [comment]
This sounds very good for me! ;) CMake as an alternative build tool is sufficient, I think.

On the side note, I've just tropped support for 2 other build systems in my 7 year old project, because they were working once, but then they rotten away. Noone used it so they had to go. I think you can do the same with CMake files _if_ they share same fate. ;)

So yeah, I'll just start a pull request!
