### ISSUE TITLE
To work with \x-formated files

### ISSUE THREAD

**Issue by MikhailKasimov** [EUA/wxHexEditor#44]
Hello!

Sometimes have to analyze files, which are given in \x format. For example ELF binaries inside of Perl-, PHP- scripts.

![php_snipped](https://cloud.githubusercontent.com/assets/7167300/23190215/4c42927c-f89f-11e6-9b19-a89eb5ddae36.png)

It'll be very useful and convenient, if wxH could work with such data: to convert, when such file is opened, and to save in plan-text strings and as binary.

Sample (ELF-header) as an example of such file: 
[hex_x.txt](https://github.com/EUA/wxHexEditor/files/791825/hex_x.txt)

![hex_x](https://cloud.githubusercontent.com/assets/7167300/23190164/0663ee90-f89f-11e6-9787-65a470dbbb00.png)

Thanks!

**Comment by EUA** [comment]
This is highly specialized request and _not_ related with **general hex editor usage.**

For my taste, this is job for "converter scripts", not a job for hex editors.
Probably could be handled with 4-5 lines of python code.
Regards.

**Comment by MikhailKasimov** [comment]
I was talking about this (long text story in short video explanation): https://www.youtube.com/watch?v=FukLQLfYfvs 

While Malzilla utility works on Windows only, the same functionality on Linux is also be appreciated. So, hope, you'll reopen this enhancement request. Thanks!

**Comment by EUA** [comment]
As I understand, you just ask "Paste as HEX" with \x00 notation.
That's OK.

**Comment by MikhailKasimov** [comment]
> As I understand, you just ask "Paste as HEX" with \x00 notation.

Yes. Reopen?

**Comment by EUA** [comment]
No.
Added support on c8d8fc9

**Comment by MikhailKasimov** [comment]
Ok, thanks!

**Comment by MikhailKasimov** [comment]
Emm... can we have the same, when we open such file in wxH?

**Comment by EUA** [comment]
How? Hex editor will show each bytes hex values.
"Interpreting" 3 chars as 1 HEX cannot be shown at "Hex Control" section.

But If you mean implement a CopyAs function as "with \x" generates string stream like "\x11\x12\x15" notation, it's possible.

**Comment by MikhailKasimov** [comment]
Preamble: "Experiments, experiments, experiments, experiments..." with Steve Balmer's intonation on his famous "Developers, developers, developers, developers...".

I've found out, that it all depends on what data-area is going to be copied -- base central or right-handed:
![hex_x](https://cloud.githubusercontent.com/assets/7167300/23190164/0663ee90-f89f-11e6-9787-65a470dbbb00.png) and this nuance is not obvious for user.

Not obvious, because when we try to select some fragment on any data-area (e.g. in central, ```5C```...), the right-handed (```\x7f```...) area is marked automatically. And vice versa -- if we select right-handed data-area , the central is marked automatically.

So, the way I found out to get binary file from ```\x7f...``` is to push 'New file' button and then fill it with our data (```\x7f```...). But here is a very important nuance: we should **explicitly** know correct size of our new file **beforehand**. Otherwise, if we define size less, than needed, we'll get wrong snippet of file. If more -- we'll have to cut redundant part off it. Workaround for this -- to automatically highlight the fragment we just pasted to -- this can help to see the border of file and cut redundant fragment in correct way, without potential corrupting file we gonna to save on disk.

> But If you mean implement a CopyAs function as "with \x" generates string stream like "\x11\x12\x15" notation, it's possible.

Yes, we haven't such possibility yet. Will be appreciated to have. Thanks!

**Comment by EUA** [comment]
in wxHexEditor, Selection is made for offset, not for screen, so it's true for both screen. Might change selection color for passive one later...

If your blinking cursor at right panel (text control - or you can say binary data area) click and copy give `\x7f` , if your cursor at hex control than "copy" command copies selected hex. Since this is natural behavior, I do not fell explain it. What is wrong with it I do not understand. English is not my main tongue.

About creating new file from selected section; Block selection size writes at last status bar section shows the selected "Block Size" at bottom of the window. Also selecting, copying and pasting to new file is not good behaviour because you can use "Save as Dump" option for binary. If you gonna copy/paste hex section, this is issue but at future you can extend file size with paste. Also you can create "big" file and delete unnecessary parts after edit,..

Adding highlight to selection is implemented right now.

**Comment by MikhailKasimov** [comment]
> Also selecting, copying and pasting to new file is not good behaviour because you can use "Save as Dump" option for binary.

All my thoughts and steps: https://www.youtube.com/watch?v=zuhZrE6cvtY

**Comment by EUA** [comment]
First of all, wxHexEditor "selects" pasted HEX or text.
Means, you can select and paste into "same file" (because pasted binary will be always smaller than actual file size.) than you can delete _remaining of the file_. After you can use **save as** to create dump. It's easy.

But "Save as dump" function with like "Copy as text, save as hex" operation is "unnatural". Not want to allow such a function.

It came to my mind that, It's possible to add "default size" into injection.
So if you want to create a new file or want to inject/insert some bytes to current file, wxHexEditor could detect last entry at clipboard and put it into dialog as a default value...

**Comment by plater** [comment]
@MikhailKasimov  Fixed in wxhexeditor-0.23+git20170228 this mornings build

**Comment by MikhailKasimov** [comment]
@plater Thanks!

**Comment by MikhailKasimov** [comment]
> Adding highlight to selection is implemented right now.

@EUA  Yet another idea -- automatically mark pasted fragment by `Quick Tag` function. This can be very useful for large fragments, when user should to scroll screen: https://www.youtube.com/watch?v=JUmTuoU0mjs

> But "Save as dump" function with like "Copy as text, save as hex" operation is "unnatural". Not want to allow such a function.

OK.

>Means, you can select and paste into "same file" (because pasted binary will be always smaller than actual file size.) than you can delete remaining of the file. After you can use save as to create dump. It's easy.

Ok, will try to twist in this way...

**Comment by EUA** [comment]
If pasted stream is to big, after paste operation wxHexEditor also scroll down and go to paste end already.
Auto tagging every pasted section might be another "feature". But then some users became unhappy due created tag files for nothing.

Instead, doesn't it better to have to see every operation in at a "change log"?
Well indeed, if you compile tool with required debug options with single middle click on mouse button you can see every action on stdout. So this is natural way to track paste operations also. This is planned feature for next releases. Just need to figure how to merge changes one byte changes and operation like deletion...

**Comment by MikhailKasimov** [comment]
>Instead, doesn't it better to have to see every operation in at a "change log"?
Well indeed, if you compile tool with required debug options with single middle click on mouse button you can see every action on stdout. So this is natural way to track paste operations also. This is planned feature for next releases. Just need to figure how to merge changes one byte changes and operation like deletion...

Let's have it too, no problem. :)
