### ISSUE TITLE
Keyboard buttons for Delete and Insert operations

### ISSUE THREAD

**Issue by MikhailKasimov** [EUA/wxHexEditor#58]
Hello!

```Insert``` keyboard button for ```Edit - Insert``` operation.
```Delete``` keyboard button for ```Edit - Delete``` operation.

've caught myself, when I try to insert some fragment or to delete it, I intuitively push ```Insert``` and ```Delete``` keyboard buttons instead of clicking icons, but they are not handled by wxH.

So, will be convenient to have this functionality too. Thanks!

**Comment by EUA** [comment]
wxHexEditor does NOT support and do not gonna support this shortcut keys.
Why?
Because they are natural "text editor" behavior. Not natural shortcuts for a hex editor.
wxHexEditor built for HUGE files, primarily.
And if you make such operations ,for example by mistake, it open big headaches...
I also think about adding extra warning messages for delete and insert (inject) operations.
So this wont be fixed at all.
