### ISSUE TITLE
To open file in tab instead of new wxH window

### ISSUE THREAD

**Issue by MikhailKasimov** [EUA/wxHexEditor#65]
Hello!

When user opens two different files via ```Open with wxH``` in its file-manager, they are to be opened in two dedicated wxH windows.

But when user opens the second file via ```Open``` in current wxH window, this file is to opened in the same wxH-window, but on dedicated tab.

So, the idea is to open the second\third\... file not in dedicated wxH windows, but in tabs of single wxH-window, when these file are to opened via ```Open with wxH``` in its file-manager.

Doable?

**Comment by EUA** [comment]
It is OK for Linux but not sure about Windows and OSX.

**Comment by EUA** [comment]
This requires IPC. Little tricky to program. But possible.

**Comment by EUA** [comment]
Okay, I implement it (but disabled for a while.)
(You can un-comment wxHexEditorApp.cpp lines 62-75 for test)

What about an user that want to have multiple instances of the program?
We must add to an option for this before enabling the code...

Also running from command client is problem because paths are not same with already running wxHexEditor and current bash client...
