### ISSUE TITLE
Feature request: configurable block size

### ISSUE THREAD

**Issue by petergeoghegan** [EUA/wxHexEditor#91]
I notice that wxHexEditor uses an ioctl() on certain platforms, BLKSSZGET, to get a page size for a block device (this happens within `src/FAL.cpp`). It would be useful to me if this was optionally configurable, at least for display/navigation purposes (the default would remain "detect", but you could hard code it to a block size of your own, specified in bytes). I would change this to 8KiB (2^13 bytes), which is the standard PostgreSQL block size. That way, I'd have an intuitive, domain-specific display for current block in wxHexEditor as I scrub through a file, something that I almost always care about.

Maybe `FAL.cpp` has responsibilities that are closely tied to opening a raw block device, so making block size configurable like this is very hard. I cannot tell from looking at the code. This would be nice to have, though. 

Thanks!

**Comment by EUA** [comment]
Hi, the time has come. :)
BLKSSZGET is only for FILE ACCESS purposes.
You know, can't start read from any offset if you are working on a device.
If you configure it, than it's possible to broke some files...

What you are asking for is: ThinSeparationLines
It's calculated at HexEditorCtrl::ReadFromBuffer@src/HexEditorCtrl.cpp
You can easily hardcode **sector_size** variable to show custom ThinSeperatorLines at HexEditor.
Customization of it? Why not. But this might be little confusing for the users since it's different than actual...

But for ordinary files... Why not? We can allow such a cosmetic via an preferences option.
Do you like to use KiB notation? :D I never got used to...

**Comment by petergeoghegan** [comment]
@EUA Great!

Many wxHexEditor users will not be interested in this feature, of course. It is interesting to me because it is totally natural for pg_hexedit + wxHexEditor to display the data as a series of blocks. The entire file is always a series of one or more fixed sized blocks, each of which has a clear beginning, middle, and end -- no exceptions. 

P.S. I usually say "KiB" because it's unambiguous

**Comment by EUA** [comment]
Instead of Custom Block Size, I add "Fake Block Size" option to preferences, looks better to me.
I also thinking of "blue" lines for fake blocks, instead of red real ones but not sure about it.
I add support for k|M|G|T extensions. So you can write 8KiB. :)
Happy testing.

**Comment by petergeoghegan** [comment]
@EUA That works well. Thanks!
